/**
 * Chat Interface Component
 * 
 * A collapsible chat panel for interacting with the AI assistant.
 * Supports mock mode when no API key is provided.
 */

import React, { useState, useRef, useEffect } from 'react';
import {
    MessageSquare,
    Send,
    Settings,
    X,
    Bot,
    User,
    Sparkles,
    Key,
    Loader2
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
    Sheet,
    SheetContent,
    SheetHeader,
    SheetTitle,
    SheetTrigger,
} from '@/components/ui/sheet';
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogDescription,
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from '@/components/ui/select';
import { useChatStore, type ApiProvider } from '@/store/chatStore';
import { useContainerStore } from '@/store/containerStore';
import { StreamParser } from '@/lib/ai/parseStream';
import { getFileTree } from '@/lib/webcontainer/container';
import { cn } from '@/lib/utils';

/**
 * Mock response that demonstrates the streaming parser
 * Creates a simple "Hello from AI" component
 */
const MOCK_RESPONSE = `I'll create a simple "Hello from AI" component to demonstrate the code generation system!

<boltArtifact id="hello-ai-demo" title="Hello from AI Demo">
  <boltAction type="file" filePath="src/components/HelloFromAI.jsx">
import React, { useState, useEffect } from 'react';

function HelloFromAI() {
  const [visible, setVisible] = useState(false);
  
  useEffect(() => {
    // Animate in after mount
    const timer = setTimeout(() => setVisible(true), 100);
    return () => clearTimeout(timer);
  }, []);

  return (
    <div style={{
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: '100vh',
      padding: '2rem',
      background: 'linear-gradient(135deg, #0f0f1a 0%, #1a1a2e 50%, #16213e 100%)',
    }}>
      <div style={{
        background: 'rgba(255,255,255,0.05)',
        borderRadius: '24px',
        padding: '3rem',
        backdropFilter: 'blur(10px)',
        border: '1px solid rgba(255,255,255,0.1)',
        textAlign: 'center',
        transform: visible ? 'translateY(0)' : 'translateY(20px)',
        opacity: visible ? 1 : 0,
        transition: 'all 0.5s ease-out',
      }}>
        <div style={{
          fontSize: '4rem',
          marginBottom: '1rem',
          animation: 'float 3s ease-in-out infinite',
        }}>
          🤖
        </div>
        <h1 style={{
          fontSize: '2.5rem',
          fontWeight: '700',
          marginBottom: '0.5rem',
          background: 'linear-gradient(135deg, #00ff88, #00d4ff, #7c3aed)',
          WebkitBackgroundClip: 'text',
          WebkitTextFillColor: 'transparent',
        }}>
          Hello from AI!
        </h1>
        <p style={{
          color: 'rgba(255,255,255,0.7)',
          fontSize: '1.1rem',
          marginBottom: '1rem',
        }}>
          This component was generated by the streaming parser.
        </p>
        <p style={{
          color: 'rgba(255,255,255,0.5)',
          fontSize: '0.9rem',
        }}>
          The code was applied in real-time during the AI response stream.
        </p>
      </div>
      <style>
        {\`
          @keyframes float {
            0%, 100% { transform: translateY(0); }
            50% { transform: translateY(-10px); }
          }
        \`}
      </style>
    </div>
  );
}

export default HelloFromAI;
  </boltAction>
  <boltAction type="file" filePath="src/App.jsx">
import React from 'react';
import HelloFromAI from './components/HelloFromAI';

function App() {
  return <HelloFromAI />;
}

export default App;
  </boltAction>
</boltArtifact>

The component has been created! It features:
- A floating robot emoji animation
- Gradient text effect
- Smooth fade-in animation
- Modern glassmorphism styling

Check the preview pane to see it in action! 🎉`;

/**
 * Simulate streaming by yielding characters with delays
 */
async function* mockStream(text: string): AsyncGenerator<string, void, unknown> {
    const words = text.split(' ');

    for (const word of words) {
        yield word + ' ';
        // Variable delay for more natural feel
        await new Promise(resolve => setTimeout(resolve, 15 + Math.random() * 25));
    }
}

/**
 * Chat message bubble component
 */
function MessageBubble({
    role,
    content,
    isStreaming
}: {
    role: 'user' | 'assistant';
    content: string;
    isStreaming?: boolean;
}) {
    const isUser = role === 'user';

    // Clean content: remove XML tags for display (show human-readable version)
    const displayContent = content
        .replace(/<boltArtifact[^>]*>/g, '\n📦 **Creating artifact...**\n')
        .replace(/<\/boltArtifact>/g, '\n✅ **Artifact complete!**\n')
        .replace(/<boltAction type="file" filePath="([^"]+)">/g, '\n📄 **Writing file:** `$1`\n```\n')
        .replace(/<boltAction type="shell">/g, '\n💻 **Running command:**\n```bash\n')
        .replace(/<\/boltAction>/g, '\n```\n');

    return (
        <div className={cn(
            "flex gap-3 p-4",
            isUser ? "flex-row-reverse" : "flex-row"
        )}>
            {/* Avatar */}
            <div className={cn(
                "flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center",
                isUser
                    ? "bg-primary/20 text-primary"
                    : "bg-gradient-to-br from-violet-500/20 to-cyan-500/20 text-cyan-400"
            )}>
                {isUser ? <User className="w-4 h-4" /> : <Bot className="w-4 h-4" />}
            </div>

            {/* Message content */}
            <div className={cn(
                "flex-1 max-w-[85%]",
                isUser && "text-right"
            )}>
                <div className={cn(
                    "inline-block p-3 rounded-2xl text-sm leading-relaxed",
                    isUser
                        ? "bg-primary text-primary-foreground rounded-br-md"
                        : "bg-muted/50 text-foreground rounded-bl-md"
                )}>
                    <div className="whitespace-pre-wrap break-words font-mono text-xs">
                        {displayContent}
                        {isStreaming && (
                            <span className="inline-block w-2 h-4 ml-1 bg-current animate-pulse" />
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}

/**
 * Settings dialog for API key configuration
 */
function SettingsDialog({
    open,
    onOpenChange
}: {
    open: boolean;
    onOpenChange: (open: boolean) => void;
}) {
    const { apiKey, apiProvider, setApiKey, setApiProvider } = useChatStore();
    const [tempKey, setTempKey] = useState(apiKey);

    const handleSave = () => {
        setApiKey(tempKey);
        onOpenChange(false);
    };

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="sm:max-w-md">
                <DialogHeader>
                    <DialogTitle className="flex items-center gap-2">
                        <Key className="w-5 h-5 text-primary" />
                        API Settings
                    </DialogTitle>
                    <DialogDescription>
                        Configure your AI provider and API key. Leave empty for mock mode.
                    </DialogDescription>
                </DialogHeader>

                <div className="space-y-4 py-4">
                    <div className="space-y-2">
                        <Label htmlFor="provider">Provider</Label>
                        <Select
                            value={apiProvider}
                            onValueChange={(v) => setApiProvider(v as ApiProvider)}
                        >
                            <SelectTrigger>
                                <SelectValue placeholder="Select provider" />
                            </SelectTrigger>
                            <SelectContent>
                                <SelectItem value="anthropic">Anthropic (Claude)</SelectItem>
                                <SelectItem value="openai">OpenAI (GPT-4)</SelectItem>
                            </SelectContent>
                        </Select>
                    </div>

                    <div className="space-y-2">
                        <Label htmlFor="apiKey">API Key</Label>
                        <Input
                            id="apiKey"
                            type="password"
                            placeholder="sk-..."
                            value={tempKey}
                            onChange={(e) => setTempKey(e.target.value)}
                        />
                        <p className="text-xs text-muted-foreground">
                            Your API key is stored locally and never sent to our servers.
                        </p>
                    </div>

                    {!apiKey && (
                        <div className="bg-amber-500/10 border border-amber-500/20 rounded-lg p-3">
                            <p className="text-xs text-amber-400 flex items-center gap-2">
                                <Sparkles className="w-4 h-4" />
                                <span>
                                    <strong>Mock Mode Active:</strong> Responses are simulated.
                                    Add an API key for real AI interactions.
                                </span>
                            </p>
                        </div>
                    )}
                </div>

                <div className="flex justify-end gap-2">
                    <Button variant="outline" onClick={() => onOpenChange(false)}>
                        Cancel
                    </Button>
                    <Button onClick={handleSave}>
                        Save Settings
                    </Button>
                </div>
            </DialogContent>
        </Dialog>
    );
}

/**
 * Main Chat Interface Component
 */
export function ChatInterface() {
    const [input, setInput] = useState('');
    const scrollRef = useRef<HTMLDivElement>(null);

    const {
        messages,
        isStreaming,
        currentStreamId,
        apiKey,
        isChatOpen,
        isSettingsOpen,
        addMessage,
        appendToMessage,
        startStreaming,
        stopStreaming,
        toggleChat,
        openSettings,
        closeSettings,
    } = useChatStore();

    const { container, setStatus, setFileTree } = useContainerStore();

    // Auto-scroll to bottom on new messages
    useEffect(() => {
        if (scrollRef.current) {
            scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
        }
    }, [messages, currentStreamId]);

    /**
     * Handle sending a message
     */
    const handleSend = async () => {
        if (!input.trim() || isStreaming) return;

        const userMessage = input.trim();
        setInput('');

        // Add user message
        addMessage({ role: 'user', content: userMessage });

        // Start streaming response
        const streamId = startStreaming();

        // Create parser connected to WebContainer
        const parser = new StreamParser(container, {
            onFileWritten: async (filePath) => {
                console.log('[Chat] File written:', filePath);
                // Refresh file tree in UI after file is written
                if (container) {
                    try {
                        const newTree = await getFileTree(container);
                        setFileTree(newTree);
                        console.log('[Chat] File tree refreshed');
                    } catch (error) {
                        console.error('[Chat] Failed to refresh file tree:', error);
                    }
                }
            },
            onShellCommand: (command) => {
                console.log('[Chat] Shell command:', command);
                // Show installing badge
                if (command.includes('npm install')) {
                    setStatus('installing');
                }
            },
            onText: (chunk) => {
                // Append chunk to streaming message
                appendToMessage(streamId, chunk);
            },
        });

        try {
            if (apiKey) {
                // TODO: Implement real API call
                // For now, fall through to mock mode
                console.log('[Chat] API key present, but using mock mode for now');
            }

            // Mock mode: stream the mock response
            for await (const chunk of mockStream(MOCK_RESPONSE)) {
                await parser.processChunk(chunk);
            }

            parser.finalize();
        } catch (error) {
            console.error('[Chat] Error:', error);
            appendToMessage(streamId, '\n\n❌ An error occurred while generating the response.');
        } finally {
            stopStreaming();
        }
    };

    /**
     * Handle Enter key press
     */
    const handleKeyDown = (e: React.KeyboardEvent) => {
        if (e.key === 'Enter' && !e.shiftKey) {
            e.preventDefault();
            handleSend();
        }
    };

    return (
        <>
            {/* Chat Toggle Button */}
            <Sheet open={isChatOpen} onOpenChange={toggleChat}>
                <SheetTrigger asChild>
                    <Button
                        size="icon"
                        className={cn(
                            "fixed bottom-6 right-6 z-50 h-14 w-14 rounded-full shadow-lg",
                            "bg-gradient-to-br from-violet-600 to-cyan-600 hover:from-violet-500 hover:to-cyan-500",
                            "transition-all duration-300",
                            isChatOpen && "scale-0 opacity-0"
                        )}
                    >
                        <MessageSquare className="h-6 w-6" />
                    </Button>
                </SheetTrigger>

                <SheetContent
                    side="right"
                    className="w-full sm:w-[450px] p-0 flex flex-col bg-background/95 backdrop-blur-xl"
                >
                    {/* Header */}
                    <SheetHeader className="p-4 border-b border-border flex-shrink-0">
                        <div className="flex items-center justify-between">
                            <SheetTitle className="flex items-center gap-2 text-lg">
                                <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-violet-500/20 to-cyan-500/20 flex items-center justify-center">
                                    <Sparkles className="w-4 h-4 text-cyan-400" />
                                </div>
                                <span className="gradient-text">AI Assistant</span>
                            </SheetTitle>
                            <div className="flex items-center gap-1">
                                <Button
                                    variant="ghost"
                                    size="icon"
                                    onClick={() => openSettings()}
                                    className="text-muted-foreground hover:text-foreground"
                                >
                                    <Settings className="w-5 h-5" />
                                </Button>
                                <Button
                                    variant="ghost"
                                    size="icon"
                                    onClick={() => toggleChat()}
                                    className="text-muted-foreground hover:text-foreground"
                                >
                                    <X className="w-5 h-5" />
                                </Button>
                            </div>
                        </div>

                        {/* Mode indicator */}
                        {!apiKey && (
                            <div className="mt-2 px-3 py-1.5 bg-amber-500/10 border border-amber-500/20 rounded-lg">
                                <p className="text-xs text-amber-400 flex items-center gap-2">
                                    <Sparkles className="w-3 h-3" />
                                    Mock Mode — Click settings to add API key
                                </p>
                            </div>
                        )}
                    </SheetHeader>

                    {/* Messages */}
                    <ScrollArea
                        ref={scrollRef}
                        className="flex-1 overflow-y-auto"
                    >
                        <div className="py-4">
                            {messages.length === 0 ? (
                                <div className="flex flex-col items-center justify-center h-64 text-center px-4">
                                    <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-violet-500/20 to-cyan-500/20 flex items-center justify-center mb-4">
                                        <Bot className="w-8 h-8 text-cyan-400" />
                                    </div>
                                    <h3 className="text-lg font-medium mb-2">Start a conversation</h3>
                                    <p className="text-sm text-muted-foreground max-w-xs">
                                        Describe what you want to build and I'll generate the code for you in real-time.
                                    </p>
                                </div>
                            ) : (
                                messages.map((msg) => (
                                    <MessageBubble
                                        key={msg.id}
                                        role={msg.role}
                                        content={msg.content}
                                        isStreaming={msg.isStreaming}
                                    />
                                ))
                            )}
                        </div>
                    </ScrollArea>

                    {/* Input */}
                    <div className="p-4 border-t border-border flex-shrink-0">
                        <div className="flex gap-2">
                            <Input
                                value={input}
                                onChange={(e) => setInput(e.target.value)}
                                onKeyDown={handleKeyDown}
                                placeholder="Describe what you want to build..."
                                disabled={isStreaming}
                                className="flex-1"
                            />
                            <Button
                                onClick={handleSend}
                                disabled={!input.trim() || isStreaming}
                                className="bg-gradient-to-r from-violet-600 to-cyan-600 hover:from-violet-500 hover:to-cyan-500"
                            >
                                {isStreaming ? (
                                    <Loader2 className="w-4 h-4 animate-spin" />
                                ) : (
                                    <Send className="w-4 h-4" />
                                )}
                            </Button>
                        </div>
                    </div>
                </SheetContent>
            </Sheet>

            {/* Settings Dialog */}
            <SettingsDialog
                open={isSettingsOpen}
                onOpenChange={(open) => open ? openSettings() : closeSettings()}
            />
        </>
    );
}
