/**
 * Inline Chat Panel Component
 * 
 * An inline chat panel with collapsible code generation sections.
 * Shows spinner during generation, with expandable details.
 */

import React, { useState, useRef, useEffect } from 'react';
import {
    Send,
    Bot,
    User,
    Sparkles,
    Loader2,
    Settings,
    ChevronDown,
    ChevronRight,
    FileCode,
    Check,
    Terminal
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { ScrollArea } from '@/components/ui/scroll-area';
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogDescription,
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from '@/components/ui/select';
import {
    Collapsible,
    CollapsibleContent,
    CollapsibleTrigger,
} from '@/components/ui/collapsible';
import { useChatStore, type ApiProvider } from '@/store/chatStore';
import { useContainerStore } from '@/store/containerStore';
import { StreamParser } from '@/lib/ai/parseStream';
import { getFileTree } from '@/lib/webcontainer/container';
import { streamOpenRouter, OPENROUTER_MODELS } from '@/lib/ai/openrouter';
import { SYSTEM_PROMPT, CHAT_SYSTEM_PROMPT } from '@/lib/ai/prompts';
import { cn } from '@/lib/utils';

/**
 * Mock response that demonstrates the streaming parser
 */
const MOCK_RESPONSE = `I'll create a simple "Hello from AI" component to demonstrate the code generation system!

<boltArtifact id="hello-ai-demo" title="Hello from AI Demo">
  <boltAction type="file" filePath="src/components/HelloFromAI.jsx">
import React, { useState, useEffect } from 'react';

function HelloFromAI() {
  const [visible, setVisible] = useState(false);
  
  useEffect(() => {
    const timer = setTimeout(() => setVisible(true), 100);
    return () => clearTimeout(timer);
  }, []);

  return (
    <div style={{
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: '100vh',
      padding: '2rem',
      background: 'linear-gradient(135deg, #0f0f1a 0%, #1a1a2e 50%, #16213e 100%)',
    }}>
      <div style={{
        background: 'rgba(255,255,255,0.05)',
        borderRadius: '24px',
        padding: '3rem',
        backdropFilter: 'blur(10px)',
        border: '1px solid rgba(255,255,255,0.1)',
        textAlign: 'center',
        transform: visible ? 'translateY(0)' : 'translateY(20px)',
        opacity: visible ? 1 : 0,
        transition: 'all 0.5s ease-out',
      }}>
        <div style={{ fontSize: '4rem', marginBottom: '1rem' }}>🤖</div>
        <h1 style={{
          fontSize: '2.5rem',
          fontWeight: '700',
          background: 'linear-gradient(135deg, #00ff88, #00d4ff, #7c3aed)',
          WebkitBackgroundClip: 'text',
          WebkitTextFillColor: 'transparent',
        }}>
          Hello from AI!
        </h1>
        <p style={{ color: 'rgba(255,255,255,0.7)', fontSize: '1.1rem' }}>
          This component was generated by the streaming parser.
        </p>
      </div>
    </div>
  );
}

export default HelloFromAI;
  </boltAction>
  <boltAction type="file" filePath="src/App.jsx">
import React from 'react';
import HelloFromAI from './components/HelloFromAI';

function App() {
  return <HelloFromAI />;
}

export default App;
  </boltAction>
</boltArtifact>

Done! Check the preview pane to see it in action! 🎉`;

async function* mockStream(text: string): AsyncGenerator<string, void, unknown> {
    const words = text.split(' ');
    for (const word of words) {
        yield word + ' ';
        await new Promise(resolve => setTimeout(resolve, 15 + Math.random() * 25));
    }
}

// Track file actions for display
interface FileAction {
    path: string;
    status: 'writing' | 'complete';
}

interface ArtifactState {
    isGenerating: boolean;
    isComplete: boolean;
    title: string;
    files: FileAction[];
}

/**
 * Collapsible artifact card showing generation progress
 */
function ArtifactCard({
    artifact,
    isExpanded,
    onToggle
}: {
    artifact: ArtifactState;
    isExpanded: boolean;
    onToggle: () => void;
}) {
    return (
        <div className="mx-2 my-2 rounded-lg border border-border bg-card overflow-hidden">
            <Collapsible open={isExpanded} onOpenChange={onToggle}>
                <CollapsibleTrigger asChild>
                    <button className="w-full flex items-center gap-2 p-2 hover:bg-muted/50 transition-colors">
                        {artifact.isGenerating ? (
                            <Loader2 className="w-4 h-4 text-cyan-400 animate-spin flex-shrink-0" />
                        ) : (
                            <Check className="w-4 h-4 text-green-400 flex-shrink-0" />
                        )}
                        <span className="text-xs font-medium flex-1 text-left truncate">
                            {artifact.isGenerating ? 'Generating code...' : artifact.title || 'Code generated'}
                        </span>
                        <span className="text-xs text-muted-foreground">
                            {artifact.files.length} file{artifact.files.length !== 1 ? 's' : ''}
                        </span>
                        {isExpanded ? (
                            <ChevronDown className="w-3.5 h-3.5 text-muted-foreground" />
                        ) : (
                            <ChevronRight className="w-3.5 h-3.5 text-muted-foreground" />
                        )}
                    </button>
                </CollapsibleTrigger>
                <CollapsibleContent>
                    <div className="border-t border-border bg-muted/30 p-2 space-y-1">
                        {artifact.files.map((file, idx) => (
                            <div key={idx} className="flex items-center gap-2 text-xs py-1 px-2 rounded bg-background/50">
                                {file.status === 'writing' ? (
                                    <Loader2 className="w-3 h-3 text-amber-400 animate-spin flex-shrink-0" />
                                ) : (
                                    <FileCode className="w-3 h-3 text-green-400 flex-shrink-0" />
                                )}
                                <span className="font-mono truncate">{file.path}</span>
                            </div>
                        ))}
                    </div>
                </CollapsibleContent>
            </Collapsible>
        </div>
    );
}

/**
 * Message bubble with smart content display
 */
function MessageBubble({
    role,
    content,
    isStreaming,
    artifact
}: {
    role: 'user' | 'assistant';
    content: string;
    isStreaming?: boolean;
    artifact?: ArtifactState | null;
}) {
    const [isExpanded, setIsExpanded] = useState(false);
    const isUser = role === 'user';

    // Extract only the text content (before/after XML tags)
    const getTextContent = (text: string) => {
        // Remove all XML content
        return text
            .replace(/<boltArtifact[\s\S]*?<\/boltArtifact>/g, '')
            .replace(/<boltArtifact[^>]*>/g, '')
            .replace(/<\/boltArtifact>/g, '')
            .replace(/<boltAction[\s\S]*?<\/boltAction>/g, '')
            .replace(/<boltAction[^>]*>/g, '')
            .replace(/<\/boltAction>/g, '')
            .trim();
    };

    const textContent = getTextContent(content);
    const hasArtifact = artifact && artifact.files.length > 0;

    if (isUser) {
        return (
            <div className="flex gap-2 p-3 flex-row-reverse">
                <div className="flex-shrink-0 w-6 h-6 rounded-full flex items-center justify-center bg-primary/20 text-primary">
                    <User className="w-3 h-3" />
                </div>
                <div className="flex-1 max-w-[85%] text-right">
                    <div className="inline-block p-2 rounded-xl text-xs leading-relaxed bg-primary text-primary-foreground rounded-br-sm">
                        {content}
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="flex gap-2 p-3 flex-row">
            <div className="flex-shrink-0 w-6 h-6 rounded-full flex items-center justify-center bg-violet-500/20 text-cyan-400">
                <Bot className="w-3 h-3" />
            </div>
            <div className="flex-1 max-w-[90%] space-y-2">
                {/* Text content */}
                {textContent && (
                    <div className="p-2 rounded-xl text-xs leading-relaxed bg-muted/50 text-foreground rounded-bl-sm">
                        <div className="whitespace-pre-wrap break-words">
                            {textContent}
                            {isStreaming && !hasArtifact && (
                                <span className="inline-block w-1.5 h-3 ml-0.5 bg-current animate-pulse" />
                            )}
                        </div>
                    </div>
                )}

                {/* Artifact card */}
                {hasArtifact && (
                    <ArtifactCard
                        artifact={artifact}
                        isExpanded={isExpanded}
                        onToggle={() => setIsExpanded(!isExpanded)}
                    />
                )}
            </div>
        </div>
    );
}

/**
 * Settings dialog
 */
function SettingsDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
    const { apiKey, apiProvider, selectedModel, setApiKey, setApiProvider, setSelectedModel } = useChatStore();
    const [tempKey, setTempKey] = useState(apiKey);

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="sm:max-w-md">
                <DialogHeader>
                    <DialogTitle>API Settings</DialogTitle>
                    <DialogDescription>Configure your AI provider and API key.</DialogDescription>
                </DialogHeader>
                <div className="space-y-4 py-4">
                    <div className="space-y-2">
                        <Label>Provider</Label>
                        <Select value={apiProvider} onValueChange={(v) => setApiProvider(v as ApiProvider)}>
                            <SelectTrigger><SelectValue /></SelectTrigger>
                            <SelectContent>
                                <SelectItem value="anthropic">Anthropic (Claude)</SelectItem>
                                <SelectItem value="openai">OpenAI (GPT-4)</SelectItem>
                                <SelectItem value="gemini">Google (Gemini)</SelectItem>
                                <SelectItem value="openrouter">OpenRouter</SelectItem>
                            </SelectContent>
                        </Select>
                    </div>

                    {apiProvider === 'openrouter' && (
                        <div className="space-y-2">
                            <Label>Model</Label>
                            <Select value={selectedModel} onValueChange={setSelectedModel}>
                                <SelectTrigger>
                                    <SelectValue placeholder="Select a model" />
                                </SelectTrigger>
                                <SelectContent>
                                    {OPENROUTER_MODELS.map((model) => (
                                        <SelectItem key={model.id} value={model.id}>
                                            <span className="font-medium">{model.name}</span>
                                            <span className="ml-2 text-muted-foreground text-xs">({model.provider})</span>
                                        </SelectItem>
                                    ))}
                                </SelectContent>
                            </Select>
                        </div>
                    )}

                    <div className="space-y-2">
                        <Label>API Key</Label>
                        <Input type="password" placeholder="sk-..." value={tempKey} onChange={(e) => setTempKey(e.target.value)} />
                    </div>
                </div>
                <div className="flex justify-end gap-2">
                    <Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>
                    <Button onClick={() => { setApiKey(tempKey); onOpenChange(false); }}>Save</Button>
                </div>
            </DialogContent>
        </Dialog >
    );
}

/**
 * Main Chat Panel
 */
export function ChatPanel() {
    const [input, setInput] = useState('');
    const [isSettingsOpen, setIsSettingsOpen] = useState(false);
    const [currentArtifact, setCurrentArtifact] = useState<ArtifactState | null>(null);
    const scrollRef = useRef<HTMLDivElement>(null);

    const {
        messages,
        isStreaming,
        currentStreamId,
        apiKey,
        apiProvider,
        selectedModel,
        chatMode,
        addMessage,
        appendToMessage,
        startStreaming,
        stopStreaming,
        setChatMode,
    } = useChatStore();

    const { container, setStatus, setFileTree } = useContainerStore();

    useEffect(() => {
        if (scrollRef.current) {
            scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
        }
    }, [messages, currentStreamId, currentArtifact]);

    const handleSend = async () => {
        if (!input.trim() || isStreaming) return;

        const userMessage = input.trim();
        setInput('');
        addMessage({ role: 'user', content: userMessage });
        const streamId = startStreaming();

        // Reset artifact state
        setCurrentArtifact(null);

        const parser = new StreamParser(container, {
            onArtifactStart: (id, title) => {
                setCurrentArtifact({
                    isGenerating: true,
                    isComplete: false,
                    title,
                    files: [],
                });
            },
            onArtifactEnd: () => {
                setCurrentArtifact(prev => prev ? { ...prev, isGenerating: false, isComplete: true } : null);
            },
            onActionStart: (type, filePath) => {
                if (type === 'file' && filePath) {
                    setCurrentArtifact(prev => prev ? {
                        ...prev,
                        files: [...prev.files, { path: filePath, status: 'writing' }],
                    } : null);
                }
            },
            onFileWritten: async (filePath) => {
                console.log('[Chat] File written:', filePath);
                // Update file status to complete
                setCurrentArtifact(prev => prev ? {
                    ...prev,
                    files: prev.files.map(f => f.path === filePath ? { ...f, status: 'complete' as const } : f),
                } : null);

                // Refresh file tree
                if (container) {
                    try {
                        const newTree = await getFileTree(container);
                        setFileTree(newTree);
                        console.log('[Chat] File tree refreshed');
                    } catch (error) {
                        console.error('[Chat] Failed to refresh file tree:', error);
                    }
                }
            },
            onShellCommand: (command) => {
                if (command.includes('npm install')) setStatus('installing');
            },
            onText: (chunk) => appendToMessage(streamId, chunk),
        });

        try {
            // Check if we should use real API or mock
            const useRealApi = apiKey && apiProvider === 'openrouter';

            if (useRealApi) {
                // Use real OpenRouter API
                console.log('[Chat] Using OpenRouter API');

                // Get conversation history for context
                const conversationHistory = messages.map(m => ({
                    role: m.role,
                    content: m.content,
                }));

                // Add current user message
                conversationHistory.push({ role: 'user', content: userMessage });

                // Select system prompt based on mode
                const systemPrompt = chatMode === 'agent' ? SYSTEM_PROMPT : CHAT_SYSTEM_PROMPT;

                // If in agent mode, we use the specific system prompt in the API call
                // But streamOpenRouter adds SYSTEM_PROMPT by default, so we need to override it or modify streamOpenRouter
                // Let's modify the messages array directly to include the correct system prompt

                const apiMessages = [
                    { role: 'system', content: systemPrompt },
                    ...conversationHistory
                ];

                await streamOpenRouter({
                    apiKey,
                    model: selectedModel as import('@/lib/ai/openrouter').OpenRouterModel,
                    messages: conversationHistory, // We'll pass history, but we need to tell streamOpenRouter which prompt to use
                    systemPromptOverride: systemPrompt,
                    onChunk: async (chunk) => {
                        await parser.processChunk(chunk);
                    },
                    onError: (error) => {
                        console.error('[Chat] OpenRouter error:', error);
                        appendToMessage(streamId, `\n\n❌ Error: ${error.message}`);
                    },
                    onComplete: () => {
                        parser.finalize();
                        console.log('[Chat] Stream complete');
                    },
                });
            } else {
                // Use mock response for demo
                console.log('[Chat] Using mock response (no API key or provider not openrouter)');
                for await (const chunk of mockStream(MOCK_RESPONSE)) {
                    await parser.processChunk(chunk);
                }
                parser.finalize();
            }
        } catch (error) {
            console.error('[Chat] Error:', error);
            appendToMessage(streamId, '\n\n❌ An error occurred.');
        } finally {
            stopStreaming();
        }
    };

    // Get artifact for the current/last assistant message
    const getArtifactForMessage = (msgId: string) => {
        if (currentStreamId === msgId) {
            return currentArtifact;
        }
        return null;
    };

    return (
        <div className="flex flex-col h-full bg-background">
            {/* Header */}
            <div className="flex items-center justify-between px-3 py-2 border-b border-border bg-card">
                <div className="flex items-center gap-2">
                    <Sparkles className="w-4 h-4 text-cyan-400" />
                    <span className="text-sm font-medium">AI Assistant</span>
                </div>

                {/* Mode Toggle */}
                <div className="flex bg-muted rounded-md p-0.5 mx-2">
                    <button
                        onClick={() => setChatMode('agent')}
                        className={cn(
                            "px-2 py-0.5 text-xs font-medium rounded-sm transition-colors",
                            chatMode === 'agent' ? "bg-background text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground"
                        )}
                    >
                        Agent
                    </button>
                    <button
                        onClick={() => setChatMode('chat')}
                        className={cn(
                            "px-2 py-0.5 text-xs font-medium rounded-sm transition-colors",
                            chatMode === 'chat' ? "bg-background text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground"
                        )}
                    >
                        Chat
                    </button>
                </div>

                <div className="flex-1" />

                <Button variant="ghost" size="icon" className="h-6 w-6" onClick={() => setIsSettingsOpen(true)}>
                    <Settings className="w-3.5 h-3.5" />
                </Button>
            </div>

            {/* Mock Mode Banner */}
            {!apiKey && (
                <div className="px-3 py-1.5 bg-amber-500/10 border-b border-amber-500/20">
                    <p className="text-xs text-amber-400 flex items-center gap-1">
                        <Sparkles className="w-3 h-3" /> Mock Mode
                    </p>
                </div>
            )}

            {/* Messages */}
            <ScrollArea ref={scrollRef} className="flex-1">
                <div className="py-2">
                    {messages.length === 0 ? (
                        <div className="flex flex-col items-center justify-center h-40 text-center px-4">
                            <Bot className="w-8 h-8 text-cyan-400 mb-2" />
                            <p className="text-xs text-muted-foreground">Describe what you want to build</p>
                        </div>
                    ) : (
                        messages.map((msg) => (
                            <MessageBubble
                                key={msg.id}
                                role={msg.role}
                                content={msg.content}
                                isStreaming={msg.isStreaming}
                                artifact={msg.role === 'assistant' ? getArtifactForMessage(msg.id) : null}
                            />
                        ))
                    )}
                </div>
            </ScrollArea>

            {/* Input */}
            <div className="p-2 border-t border-border">
                <div className="flex gap-1.5">
                    <Input
                        value={input}
                        onChange={(e) => setInput(e.target.value)}
                        onKeyDown={(e) => e.key === 'Enter' && !e.shiftKey && (e.preventDefault(), handleSend())}
                        placeholder="Ask AI..."
                        disabled={isStreaming}
                        className="flex-1 h-8 text-xs"
                    />
                    <Button
                        onClick={handleSend}
                        disabled={!input.trim() || isStreaming}
                        size="icon"
                        className="h-8 w-8 bg-gradient-to-r from-violet-600 to-cyan-600"
                    >
                        {isStreaming ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Send className="w-3.5 h-3.5" />}
                    </Button>
                </div>
            </div>

            <SettingsDialog open={isSettingsOpen} onOpenChange={setIsSettingsOpen} />
        </div>
    );
}
